.PHONY: install dev build lint format test

install:
		npm ci

dev:
		npm run dev

run: dev
	@echo "Running frontend"

convert:
		npm run convert

build:
		npm run build

lint:
		npm run lint

format:
		npm run format

test:
		npm run test
