# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

'on':
  push:
    branches:
      - dev
    tags: ['v*.*.*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.4.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      # Optional inputs can be passed here
      ORG: epfl-lgb
      REPO: lgb-trsc
      build_context: '[ "./frontend"]'